---
- name: Install required packages
  apt:
    name:
      - openjdk-21-jre-headless
      - wget
      - screen
    update_cache: yes

- name: Create minecraft user
  user:
    name: minecraft
    create_home: yes
    shell: /bin/bash

- name: Create minecraft directory
  file:
    path: /home/minecraft/server
    state: directory
    owner: minecraft
    group: minecraft
    mode: '0755'

- name: Download latest Minecraft server JAR
  block:
    - name: Download Minecraft server jar
      get_url:
        url: https://piston-data.mojang.com/v1/objects/05e4b48fbc01f0385adb74bcff9751d34552486c/server.jar
        dest: /home/minecraft/server/server.jar
        mode: '0644'
  become: true

- name: Accept EULA
  copy:
    dest: /home/minecraft/server/eula.txt
    content: "eula=true\n"
    owner: minecraft
    group: minecraft
    mode: '0644'

- name: Create systemd service for Minecraft
  copy:
    dest: /etc/systemd/system/minecraft.service
    content: |
      [Unit]
      Description=Minecraft Server
      After=network.target

      [Service]
      User=minecraft
      WorkingDirectory=/home/minecraft/server
      ExecStart=/usr/bin/java -Xmx2048M -Xms2048M -jar server.jar nogui
      Restart=always

      [Install]
      WantedBy=multi-user.target
  notify: restart minecraft

- name: Enable and start Minecraft service
  systemd:
    name: minecraft
    enabled: yes
    state: started
